class Sun extends Entity {
    // If targetY is provided, it's generated by a sunflower. 
    // If not, it falls from the sky to a random targetY.
    constructor(game, x, y, targetY = null) {
        super(game, x, y);
        this.value = 25;
        this.radius = 25; // Hitbox radius
        this.speed = 50; // Fall speed
        
        if (targetY === null) {
            this.targetY = game.board.offsetY + Math.random() * (game.board.rows * game.board.cellHeight - 50);
        } else {
            this.targetY = targetY;
        }
        
        this.state = 'FALLING'; // FALLING, GROUND, COLLECTED
        this.lifeTime = 0;
        this.maxLife = 10;
        
        this.element.src = 'assets/images/interface/Sun.gif';
        this.element.style.width = '78px';
        this.element.style.height = '78px';
        this.element.style.cursor = 'pointer';
        this.element.style.pointerEvents = 'auto'; // allow direct clicking!
        
        // Add direct click event listener
        this.element.addEventListener('mousedown', (e) => {
            // Prevent UI manager from getting confused
            if (!this.game.inputManager.selectedSeed && !this.game.inputManager.isShovelSelected) {
                e.stopPropagation();
                this.collect();
            }
        });
    }
    
    update(deltaTime) {
        super.update(deltaTime);
        
        if (this.state === 'FALLING') {
            this.y += this.speed * deltaTime;
            if (this.y >= this.targetY) {
                this.y = this.targetY;
                this.state = 'GROUND';
            }
        } 
        else if (this.state === 'GROUND') {
            this.lifeTime += deltaTime;
            if (this.lifeTime >= 0.5) { // Auto collect after 0.5 seconds on ground
                this.collect();
            }
            if (this.lifeTime >= this.maxLife) {
                this.isDead = true;
            }
        }
        else if (this.state === 'COLLECTED') {
            // Move towards top-left corner (Sun Bank)
            const dx = 50 - this.x;
            const dy = 30 - this.y;
            const dist = Math.hypot(dx, dy);
            
            if (dist < 10) {
                this.isDead = true;
                this.game.addSun(this.value);
            } else {
                const moveSpeed = 500 * deltaTime;
                this.x += (dx / dist) * moveSpeed;
                this.y += (dy / dist) * moveSpeed;
            }
        }
    }
    
    collect() {
        if (this.state !== 'COLLECTED') {
            this.state = 'COLLECTED';
            this.game.audioManager.play('sun');
        }
    }
}
